dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
  - clang
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - gcc-6
      - g++-6
      - cmake
script:
  # Link gcc-6 and g++-6 to their standard commands
  #- sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  #- sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  #- export CC=/usr/bin/gcc-6
  #- export CXX=/usr/bin/g++-6
  # Check versions of gcc, g++ and cmake
  #- gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - cmake ./CMakeLists.txt
  - make
  - make CTEST_OUTPUT_ON_FAILURE=1 test